 provisioner "remote-exec" {

      connection {

         type = "ssh"
         user = "centos"
         private_key = "${file(var.PATH_TO_PRIVATE_KEY)}"
         host = "${self.public_ip}"

      }

   }

 provisioner "local-exec" {

   command = "ansible-playbook -u centos -i '${self.public_ip},' --private-key ${var.PATH_TO_PRIVATE_KEY} jenkins_server_preparation.yml --tags=jenkins"

 }
